baseurl = "https://mm-git.github.io"
languageCode = "en-us"
title = "CODE HOUSE"
author = "Motoyasu Meguro"
copyright = "&copy; 2016 code-house.jp"
theme = "hugo-uno"

[Params]
description = "I'm Motoyasu, freelance software engineer."
github = "mm-git"
facebook = "motoyasu.meguro"
linkedin = "meguro"
cover = "images/background.jpg"
