baseurl = "https://code-house.jp/"
languageCode = "en-us"
title = "CODE HOUSE"
author = "CODE HOUSE"
copyright = "Powered by Hugo. Copyright © 2016 code-house.jp"
theme = "hugo-uno"
canonifyurls = true
hasCJKLanguage = true
pygmentscodefences = true
pygmentsstyle = "solarizedlight"
PygmentsOptions = "linenos=table,nobackground=true"

[Params]
description = "Hello, I'm a freelance software engineer."
github = "mm-git"
facebook = "motoyasu.meguro"
linkedin = "meguro"
cover = "/images/background.jpg"
logo = "/images/codehouse_logo.png"
