baseurl = "https://mm-git.github.io/"
languageCode = "en-us"
title = "CODE HOUSE"
author = "Motoyasu Meguro"
copyright = "Powered by Hugo. Copyright © 2016 code-house.jp"
theme = "hugo-uno"
canonifyurls = true
hasCJKLanguage = true
pygmentscodefences = true
pygmentsstyle = "solarizedlight"

[Params]
description = "I'm Motoyasu, a freelance software engineer."
github = "mm-git"
facebook = "motoyasu.meguro"
linkedin = "meguro"
cover = "/images/background.jpg"
logo = "/images/codehouse_logo.png"
